# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3500m

group=noobanidus.mods.gsu
shadow_group=noobanidus.mods.gsu
version=0.4.11.20

mod_name=Generic Stream Utilities
mod_author=Noobanidus
mod_id=gsu
mod_homepage=https://www.curseforge.com/minecraft/mc-mods/gsu
mod_source=https://github.com/noobanidus/gsu
mod_issues=https://github.com/noobanidus/gsu/issues
mod_description=Provides a series of potions, commands, enchantments and other effects for Twitch streamer integration with Minecraft.
mod_license=mit
mixin_id=gsu

# ForgeGradle properties (gradle/forge.gradle)
minecraft_version=1.21
neo_version=21.0.114-beta
minecraft_version_range=[1.21)
neo_version_range=[21.0,)
loader_version_range=[2,)

forge_at=src/main/resources/META-INF/accesstransformer.cfg

# curseforge properties (gradle/curseforge.gradle)
curse_project=499315
curse_page=https://www.curseforge.com/minecraft/mc-mods/gsu
curse_release_type=release
curse_versions=1.21, 1.21.1
java_21=true

git_previous_commit=8c2699632ef96299a4d11a853c8d6648981b50b7

