# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.217
neo_version_range=[21.1.200,)
loader_version_range=[2,)
jei_version=19.27.0.340
curios_version=9.2.2+1.21.1
auto_service_version=1.0.1

mod_id=gsu
mod_name=Generic Streamer Utilities
mod_license=MIT
mod_version=1.5.12.23
mod_group_id=noobanidus.mods
mod_authors=Noobanidus
mod_description=Provides a series of potions, commands, enchantments and other effects for Twitch streamer integration with Minecraft.

mixin_extras=0.5.0

curse_project=499315
curse_page=https://www.curseforge.com/minecraft/mc-mods/gsu
curse_release_type=release
curse_versions=1.21, 1.21.1, NeoForge
java_21=true
curse_slug=gsu

git_previous_commit=8309f2c5b898a99a436ed7fac99f9a7b147b6fb0