modLoader="javafml" 
loaderVersion="[36,)" 
issueTrackerURL="https://github.com/noobanidus/gsu/issues"
license="https://github.com/noobanidus/gsu/blob/1.16/LICENSE"
[[mods]] 
modId="gsu"
version="${version}"
displayName="Generic Stream Utilities"
displayURL="https://minecraft.curseforge.com/projects/gsu"
credits=""
authors="Noobanidus"
description='''
Provides a series of potions, commands, enchantments and other effects for Twitch streamer integration with Minecraft.
'''
[[dependencies.gsu]]
    modId="forge"
    mandatory=true
    versionRange="[36.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gsu]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"
